name: Create Voice

permissions:
  contents: read


on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
      text:
        description: "text"
        required: true
      voice:
        description: "voice"
        default: "en-US-EmmaMultilingualNeural"

      pitch:
        description: "pitch"
        default: "+0Hz"
      rate:
        description: "rate"
        default: "+0%"
      volume:
        description: "volume"
        default: "+0%"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Process
        run: |
          printf "%s" "${{ inputs.text }}" > input.txt
          python main.py ${{ inputs.name}} -v ${{ inputs.voice }} -p ${{ inputs.pitch }} -r ${{ inputs.rate }} -vol ${{ inputs.volume }}
