name: t2p

on:
  workflow_dispatch:
    inputs:
      text:
        description: "text"
        required: true

jobs:
  tts_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download TTS Executable
        run: |
          wget -O tts.tar.gz "https://github.com/tcp2/edge-tts-go/releases/download/1.0.0/tts-1.0.0-linux-amd64.tar.gz"
          tar -xzvf tts.tar.gz
          chmod +x tts

      - name: Convert Text to Speech
        run: ./tts --text "${{ github.event.inputs.text }}" --voice vi-VN-NamMinhNeural --rate 0% --pitch 0Hz --write-media speech.mp3

      - name: Upload to API
        run: |
          curl -X POST "https://minhvh-n8.hf.space/webhook/upload" \
          -F "file=@speech.mp3"