name: Create Voice

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      uid:
        description: "uid"
        required: true
      name:
        description: "name"
        required: true
      text:
        description: "text"
        required: true
      voice:
        description: "voice"
        default: "en-US-EmmaMultilingualNeural"
      pitch:
        description: "pitch"
        default: "+0Hz"
      rate:
        description: "rate"
        default: "+0%"
      volume:
        description: "volume"
        default: "+0%"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Process
        run: |
          printf "%s" "${{ inputs.text }}" > input.txt
          python main.py ${{ inputs.name}} \
           -v ${{ inputs.voice }} \
           -p ${{ inputs.pitch }} \
           -r ${{ inputs.rate }} \
           -vol ${{ inputs.volume }}

  notify:
    runs-on: ubuntu-latest
    needs: run-script
    if: always()
    steps:
      - name: Send notification
        run: |
          STATUS="${{ job.status }}"
          WORKFLOW="${{ github.workflow }}"
          REPO="${{ github.repository }}"
          RUN_ID="${{ github.run_id }}"
          URL="https://github.com/$REPO/actions/runs/$RUN_ID"

          curl -s -X POST https://laobo.xyz/gh_action/${{inputs.uid}} \
          -d status="${{job.status}}"" \
          -d run_id="${{ github.run_id }}"
